Repository keepsaker/back-memory, pull requests merged in 2023-08, with the labels that each got.

#5 [BE] feat: 추억을 새긴다
  our-memory/build.gradle
  our-memory/src/main/java/keepsake/ourmemory/api/memory/MemoryController.java
  our-memory/src/main/java/keepsake/ourmemory/api/memory/MemoryCreateRequest.java
  our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
  our-memory/src/main/java/keepsake/ourmemory/domain/memory/Category.java
  our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
  our-memory/src/main/java/keepsake/ourmemory/domain/memory/Title.java
  our-memory/src/main/java/keepsake/ourmemory/repository/MemoryRepository.java
  our-memory/src/test/java/keepsake/ourmemory/api/MemoryControllerTest.java
  our-memory/src/test/java/keepsake/ourmemory/application/MemoryServiceTest.java
  our-memory/src/test/java/keepsake/ourmemory/domain/memory/CategoryTest.java
  our-memory/src/test/java/keepsake/ourmemory/domain/memory/StarTest.java
Labels: feature, test

#16 [BE] chore: DB-setting
  our-memory/src/main/java/keepsake/ourmemory/application/memory/MemoryService.java
  our-memory/src/main/java/keepsake/ourmemory/domain/memory/Memory.java
  our-memory/src/main/java/keepsake/ourmemory/ui/MemoryController.java
  our-memory/src/main/java/keepsake/ourmemory/ui/dto/response/SingleMemoryResponse.java
  our-memory/src/main/resources/application.yml
  our-memory/src/test/java/keepsake/ourmemory/acceptance/memory/MemoryAcceptanceTest.java
  our-memory/src/test/java/keepsake/ourmemory/application/memory/MemoryServiceMockTest.java
  our-memory/src/test/java/keepsake/ourmemory/application/memory/MemoryServiceTest.java
Labels: infra

#19 hotfix: CORS 설정 및 application.yml 프로파일 분리
  our-memory/src/main/java/keepsake/ourmemory/config/WebMvcConfig.java
  our-memory/src/main/resources/application.yml
Labels: bug, refactor
